(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={progress:Math.max(1,+localStorage.getItem('bug_progress')||1),coins:+localStorage.getItem('bug_coins')||0,level:1,x:205,y:590,solved:false,vision:false,inventory:[],step:0};
const levels=[
{title:'Itning ogohlantirishi',hint:'Sariq daraxt tagida nimadir yaltirayapti.',story:'Dog shahardagi birinchi sirni ko‘rsatdi.',type:'key'},
{title:'Signal chiroqlari',hint:'Ranglar ketma-ketligini diqqat bilan kuzat.',story:'Elektr tizimi kimdir tomonidan o‘zgartirilgan.',type:'lights'},
{title:'Qulf kodi',hint:'2, 4, 8 ... keyingi son nima?',story:'Devor ortida “B.T. LAB” yozuvi topildi.',type:'code'},
{title:'Ko‘rinmas izlar',hint:'👁 tugmasini bosib yashirin izlarni ko‘r.',story:'Izlar yer osti laboratoriyasiga olib boradi.',type:'vision'},
{title:'Dori formulasi',hint:'Devor yozuvi: barg → lampochka → kolba.',story:'Mimi vaqtinchalik antidot formulasini topdi.',type:'mix'},
{title:'Soxta portret',hint:'Portretni bir marta emas, ikki marta tekshir.',story:'Portret ortida yashirin tunnel rejasi bor edi.',type:'portrait'},
{title:'Xotira xonasi',hint:'Bir xil belgilar juftligini top.',story:'Shahar belgilarida hasharot kodi yashiringan.',type:'memory'},
{title:'Soyalar',hint:'Qaysi soya haqiqiy tarakanga mos?',story:'Mutatsiya izlari yanada ko‘paymoqda.',type:'shadow'},
{title:'Ko‘zgudagi raqam',hint:'Ko‘zgudagi raqamni teskari o‘qib ko‘r.',story:'7312 kodi markaziy liftga tegishli ekan.',type:'mirror'},
{title:'Boss: Roach Rush',hint:'15 soniyada 5 ta tarakanni tut!',story:'Mimi Green Districtni tozaladi. Ammo bu faqat boshlanishi...',type:'rush'}];
const frames=['assets/walk1.webp','assets/walk2.webp','assets/walk3.webp'];
function save(){localStorage.setItem('bug_progress',state.progress);localStorage.setItem('bug_coins',state.coins)}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');if(id==='#home')refreshHome();if(id==='#map')renderMap()}
function refreshHome(){$('#homeProgress').textContent=`${state.progress}/100`;$('#homeCoins').textContent=state.coins}
function renderMap(){
 $('#mapCoins').textContent=state.coins;const root=$('#chapters');root.innerHTML='';
 const names=['🌿 Green District','🧪 Old Laboratory','🚇 Underground','🏭 Factory','🌙 Night Block','🏥 Abandoned Clinic','📡 Signal Tower','🕳 Deep Nest','🧬 Mutation Core','👑 Final Hive'];
 for(let c=0;c<10;c++){const box=document.createElement('section');box.className='chapter';box.innerHTML=`<h3>${names[c]}</h3><div class="levels"></div>`;const grid=box.querySelector('.levels');for(let i=1;i<=10;i++){const n=c*10+i,b=document.createElement('button');b.className='level '+(n<state.progress?'done':n===state.progress?'current':'locked');b.innerHTML=`${n}${n<state.progress?'<span class="mini-star">⭐</span>':''}`;if(n<=Math.min(state.progress,10))b.onclick=()=>startLevel(n);grid.appendChild(b)}root.appendChild(box)}
}
$('#continueBtn').onclick=()=>startLevel(Math.min(state.progress,10));$('#mapBtn').onclick=()=>show('#map');$('#backHome').onclick=()=>show('#home');$('#backMap').onclick=()=>show('#map');
function baseScene(){$('#sceneObjects').innerHTML=`<div class="tree" style="right:39px;bottom:152px"></div><div class="roach" style="left:35px;top:286px">🪳</div>`}
function startLevel(n){if(n>10){toast('Keyingi eshiklar tez orada!');return}state.level=n;state.solved=false;state.vision=false;state.inventory=[];state.x=205;state.y=Math.max(455,innerHeight-290);show('#game');baseScene();$('#world').classList.remove('vision-on');$('#girl').classList.remove('vision');$('#visionBtn').style.display=levels[n-1].type==='vision'?'block':'none';$('#door').classList.remove('open');$('#complete').classList.remove('show');$('#puzzle').classList.remove('show');$('#levelTag').textContent=`ESHIK ${n} · ${levels[n-1].title}`;placeGirl();setupLevel(n);message(n===1?'🐶 Dog: “Mimi! Daraxt yonini tekshir. Nimadir yaltirayapti!”':`🔎 ${levels[n-1].title}`)}
function placeGirl(){const w=$('#world').clientWidth,h=$('#world').clientHeight;state.x=Math.max(4,Math.min(w-100,state.x));state.y=Math.max(130,Math.min(h-145,state.y));$('#girl').style.left=state.x+'px';$('#girl').style.top=state.y+'px'}
function animateGirl(){const g=$('#girl');g.src=frames[state.step%frames.length];clearTimeout(g._idle);g._idle=setTimeout(()=>g.src='assets/idle.webp',150)}
function move(dx,dy){state.x+=dx;state.y+=dy;state.step++;placeGirl();animateGirl();checkDoor()}
$$('.dpad button').forEach(b=>{let timer;const d=b.dataset.dir,go=()=>move(d==='left'?-18:d==='right'?18:0,d==='up'?-18:d==='down'?18:0);b.onpointerdown=e=>{e.preventDefault();go();timer=setInterval(go,110)};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>clearInterval(timer)});
addEventListener('keydown',e=>{if(!$('#game').classList.contains('active'))return;const k=e.key.toLowerCase();if(k==='arrowup'||k==='w')move(0,-18);if(k==='arrowdown'||k==='s')move(0,18);if(k==='arrowleft'||k==='a')move(-18,0);if(k==='arrowright'||k==='d')move(18,0);if(k==='e'||k===' ')action()});
$('#hintBtn').onclick=()=>message('💡 '+levels[state.level-1].hint);$('#actionBtn').onclick=action;$('#visionBtn').onclick=()=>{state.vision=!state.vision;$('#world').classList.toggle('vision-on',state.vision);$('#girl').classList.toggle('vision',state.vision);if(state.vision)message('👁 Mimi yashirin izlarni ko‘ryapti!')};
function near(el,dist=118){const a=el.getBoundingClientRect(),g=$('#girl').getBoundingClientRect();return Math.hypot(a.left+a.width/2-g.left-g.width/2,a.top+a.height/2-g.top-g.height/2)<dist}
function action(){const x=$$('.interact,.collectible,.hidden-switch').find(e=>e.offsetParent!==null&&near(e));if(x)x.click();else message('Bu yerda hozircha hech narsa yo‘q...')}
function checkDoor(){if(state.solved&&near($('#door'),130))finishLevel()}
function setupLevel(n){const o=$('#sceneObjects'),type=levels[n-1].type;
 if(type==='key'){o.insertAdjacentHTML('beforeend',`<div class="dog" style="left:58px;bottom:202px">🐶</div><button class="interact spark" id="keySpot" style="right:35px;bottom:136px;width:92px;height:92px"></button>`);$('#keySpot').onclick=()=>{state.solved=true;$('#keySpot').remove();toast('🔑 Kalit topildi!');message('Eshik ochiq. Tepaga boring!')}}
 if(type==='lights'){o.insertAdjacentHTML('beforeend',`<div class="clue" style="left:32px;top:320px">⚡ 4 SIGNAL</div><button class="interact spark" id="console" style="left:160px;top:300px;width:115px;height:100px"></button>`);$('#console').onclick=openLights}
 if(type==='code'){o.insertAdjacentHTML('beforeend',`<div class="clue" style="left:24px;top:282px;font-size:23px">2 → 4 → 8 → ?</div><button class="interact spark" id="keypad" style="right:105px;top:275px;width:90px;height:110px"></button>`);$('#keypad').onclick=()=>openCode('16')}
 if(type==='vision'){o.insertAdjacentHTML('beforeend',`<div class="footprint" style="left:125px;top:520px">👣</div><div class="footprint" style="left:205px;top:440px">👣</div><div class="footprint" style="left:285px;top:355px">👣</div><button class="hidden-switch" id="secret" style="right:63px;top:276px"></button>`);$('#secret').onclick=()=>{state.solved=true;toast('🔘 Yashirin tugma!');message('Mexanizm ishga tushdi. Eshikka boring.')}}
 if(type==='mix'){o.insertAdjacentHTML('beforeend',`<div class="clue" style="left:24px;top:280px">🌿 → 💡 → 🧪</div><button class="collectible" data-item="🌿" style="left:61px;top:425px">🌿</button><button class="collectible" data-item="💡" style="right:67px;top:395px">💡</button><button class="collectible" data-item="🧪" style="left:205px;top:535px">🧪</button>`);$$('.collectible').forEach(b=>b.onclick=()=>{if(!state.inventory.includes(b.dataset.item)){state.inventory.push(b.dataset.item);b.remove();toast(b.dataset.item+' olindi');if(state.inventory.length===3)openMix()}})}
 if(type==='portrait'){o.insertAdjacentHTML('beforeend',`<div class="clue" style="left:50%;top:300px;transform:translateX(-50%);font-size:34px">🖼️</div><button class="interact spark" id="portrait" style="left:50%;top:285px;transform:translateX(-50%);width:95px;height:95px"></button>`);let taps=0;$('#portrait').onclick=()=>{taps++;if(taps===1)message('Oddiy portretga o‘xshaydi... yana tekshirish kerakdir?');else{state.solved=true;toast('🔘 Portret ortida tugma!');message('Tunnel qulfi ochildi.')}}}
 if(type==='memory'){o.insertAdjacentHTML('beforeend',`<div class="clue" style="left:150px;top:337px">🧠 MEMORY</div><button class="interact spark" id="memoryBox" style="left:145px;top:305px;width:140px;height:120px"></button>`);$('#memoryBox').onclick=openMemory}
 if(type==='shadow'){o.insertAdjacentHTML('beforeend',`<div class="clue" style="left:118px;top:335px">Qaysi soya haqiqiy?</div><button class="interact spark" id="shadowWall" style="left:110px;top:300px;width:205px;height:130px"></button>`);$('#shadowWall').onclick=openShadow}
 if(type==='mirror'){o.insertAdjacentHTML('beforeend',`<div class="clue" style="left:145px;top:315px;font-size:31px;transform:scaleX(-1)">7312</div><button class="interact spark" id="mirror" style="left:130px;top:285px;width:175px;height:130px"></button>`);$('#mirror').onclick=()=>openCode('7312')}
 if(type==='rush'){o.insertAdjacentHTML('beforeend',`<div class="clue" style="left:155px;top:345px">🚨 BOSS</div><button class="interact spark" id="alarm" style="left:145px;top:310px;width:140px;height:120px"></button>`);$('#alarm').onclick=openRush}
}
function shell(title,body){$('#puzzle').innerHTML=`<div class="panel"><button class="close">×</button><h3>${title}</h3>${body}</div>`;$('#puzzle').classList.add('show');$('.close').onclick=()=>$('#puzzle').classList.remove('show')}
function openLights(){const colors=['#ff695a','#f2d44c','#61b5ff','#9bd36b'],seq=[0,2,1,3],input=[];shell('Signalni takrorla',`<p>Ketma-ketlikni eslab qol.</p><div class="lights">${colors.map((c,i)=>`<button class="light" data-i="${i}" style="background:${c}"></button>`).join('')}</div><button class="btn" id="playSeq" style="width:100%">SIGNALNI KO‘RISH</button>`);const lights=$$('.light');$('#playSeq').onclick=async()=>{input.length=0;for(const i of seq){lights[i].classList.add('on');await wait(430);lights[i].classList.remove('on');await wait(170)}};lights.forEach(l=>l.onclick=()=>{input.push(+l.dataset.i);l.classList.add('on');setTimeout(()=>l.classList.remove('on'),170);const i=input.length-1;if(input[i]!==seq[i]){input.length=0;toast('Xato, qayta urinib ko‘r');return}if(input.length===seq.length)solve('⚡ To‘g‘ri signal!')})}
function openCode(answer){let val='';shell('Kodli qulf',`<p>Ishoraga qarab kodni kiriting.</p><div class="code-display" id="codeDisplay">----</div><div class="keys">${[1,2,3,4,5,6,7,8,9,'⌫',0,'✓'].map(x=>`<button class="key" data-k="${x}">${x}</button>`).join('')}</div>`);$$('.key').forEach(k=>k.onclick=()=>{const x=k.dataset.k;if(x==='⌫')val=val.slice(0,-1);else if(x==='✓'){if(val===answer)solve('🔐 Kod to‘g‘ri!');else{toast('Kod noto‘g‘ri');val=''}}else if(val.length<4)val+=x;$('#codeDisplay').textContent=val||'----'})}
function openMix(){let mix=[];shell('Antidot formulasi',`<p>Ingredientlarni to‘g‘ri tartibda bosing.</p><div class="mix-row">${['🌿','💡','🧪'].map(x=>`<button class="mix" data-m="${x}">${x}</button>`).join('')}</div><div class="code-display" id="mixDisplay" style="letter-spacing:2px">?</div>`);$$('.mix').forEach(b=>b.onclick=()=>{mix.push(b.dataset.m);$('#mixDisplay').textContent=mix.join(' + ');if(mix.length===3){if(mix.join('')==='🌿💡🧪')solve('🧪 Antidot tayyor!');else{toast('Formula buzildi');mix=[];$('#mixDisplay').textContent='?'}}})}
function openMemory(){const icons=['🪳','🔑','🧪','👁','🪳','🔑','🧪','👁'].sort(()=>Math.random()-.5);let open=[],matched=0;shell('Xotira xonasi',`<p>4 ta juftlikni top.</p><div class="memory">${icons.map(x=>`<button class="card" data-v="${x}">${x}</button>`).join('')}</div>`);$$('.card').forEach(c=>c.onclick=()=>{if(c.classList.contains('flip')||c.classList.contains('match')||open.length===2)return;c.classList.add('flip');open.push(c);if(open.length===2)setTimeout(()=>{if(open[0].dataset.v===open[1].dataset.v){open.forEach(x=>x.classList.add('match'));matched+=2;if(matched===8)solve('🧠 Barcha juftlik topildi!')}else open.forEach(x=>x.classList.remove('flip'));open=[]},520)})}
function openShadow(){shell('Soyani top',`<p>Haqiqiy tarakanga mos soyani tanlang.</p><div style="font-size:45px;text-align:center">🪳</div><div class="small-grid"><button class="choice">🦋</button><button class="choice" data-ok="1" style="filter:grayscale(1) brightness(.15)">🪳</button><button class="choice">🦂</button><button class="choice">🐞</button></div>`);$$('.choice').forEach(b=>b.onclick=()=>b.dataset.ok?solve('🪳 To‘g‘ri soya!'):toast('Bu emas'))}
function openRush(){let left=15,hits=0;shell('ROACH RUSH',`<p>15 soniyada 5 ta tarakanni tut!</p><div class="timer" id="timer">15</div><div id="rushArea" style="position:relative;height:290px;border:3px solid var(--ink);border-radius:15px;background:#4c974b;overflow:hidden"></div>`);const area=$('#rushArea'),spawn=()=>{if(hits>=5)return;area.innerHTML='';const b=document.createElement('button');b.textContent='🪳';b.style.cssText=`position:absolute;left:${Math.random()*80}%;top:${Math.random()*74}%;font-size:42px;border:0;background:transparent`;b.onclick=()=>{hits++;toast(hits+'/5');spawn()};area.appendChild(b)};spawn();const iv=setInterval(()=>{left--;$('#timer').textContent=left;if(left<=0){clearInterval(iv);if(hits>=5)solve('🚨 Hudud tozalandi!');else{$('#puzzle').classList.remove('show');toast('Vaqt tugadi')}}},1000)}
function solve(t){state.solved=true;$('#puzzle').classList.remove('show');toast(t);message('✅ Mexanizm ochildi. Eshikka boring!')}
function finishLevel(){if($('#complete').classList.contains('show'))return;$('#door').classList.add('open');state.coins+=10;if(state.level===state.progress&&state.progress<100)state.progress++;save();setTimeout(()=>{$('#completeText').textContent=levels[state.level-1].story;$('#complete').classList.add('show')},650)}
$('#nextBtn').onclick=()=>state.level<10?startLevel(state.level+1):show('#map');
function message(t){const m=$('#message');m.textContent=t;m.classList.add('show');clearTimeout(m._t);m._t=setTimeout(()=>m.classList.remove('show'),3900)}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1600)}
const wait=ms=>new Promise(r=>setTimeout(r,ms));refreshHome();
})();
